In [4]:
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.linear_model import Lasso
from sklearn.model_selection import KFold, cross_val_score

import pandas as pd
import numpy as np
import optuna

import os

In [5]:
data = pd.read_csv('../data/processed/train.csv')

X_train = data.drop(columns=['LogSalePrice'])
y_train = data['LogSalePrice']

In [6]:
cv = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# XGBoost

In [7]:
def objective_xgb(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 300, 2000, step=100),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
        'max_depth': trial.suggest_int('max_depth', 2, 6),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.2, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 1.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
    }
    
    model = XGBRegressor(
        **params,
        random_state=42,
        n_jobs=-1
    )
    
    scores = cross_val_score(
        model, 
        X_train, 
        y_train, 
        cv=cv, 
        scoring='neg_root_mean_squared_error'
    )

    return -scores.mean()

In [8]:
study_xgb = optuna.create_study(
    direction='minimize',  # минимизируем RMSE
    sampler=optuna.samplers.TPESampler(seed=42)
)

study_xgb.optimize(objective_xgb, n_trials=50)
print('Best RMSE: ', study_xgb.best_value)
print('Best params: ', study_xgb.best_params)

[I 2026-10-26 17:21:49,639] A new study created in memory with name: no-name-9d4dadd5-8d7a-4bcf-bb87-bad9a611f164
[I 2026-10-26 17:21:59,856] Trial 0 finished with value: 0.14476862794054746 and parameters: {'n_estimators': 900, 'learning_rate': 0.0862735828664018, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.32479561626896214, 'reg_alpha': 2.9152036385288193e-08, 'reg_lambda': 0.6245760287469893}. Best is trial 0 with value: 0.14476862794054746.
[I 2026-10-26 17:22:11,944] Trial 1 finished with value: 0.13716400917899949 and parameters: {'n_estimators': 1300, 'learning_rate': 0.04170553216181044, 'max_depth': 2, 'min_child_weight': 10, 'subsample': 0.9162213204002109, 'colsample_bytree': 0.36987128854262097, 'reg_alpha': 2.8483918709107956e-07, 'reg_lambda': 4.4734294104626844e-07}. Best is trial 1 with value: 0.13716400917899949.
[I 2026-10-26 17:22:20,404] Trial 2 finished with value: 0.13430261411320069 and parameters: {'n_estimators': 800, 'learning_rate': 0.02408207265453543, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.8059264473611898, 'colsample_bytree': 0.3115950885216335, 'reg_alpha': 2.1734877073417355e-06, 'reg_lambda': 1.9826980964985924e-05}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:22:30,765] Trial 3 finished with value: 0.13765715011090424 and parameters: {'n_estimators': 1100, 'learning_rate': 0.05254210669345883, 'max_depth': 2, 'min_child_weight': 6, 'subsample': 0.7962072844310213, 'colsample_bytree': 0.2371603301759982, 'reg_alpha': 0.0007250347382396634, 'reg_lambda': 3.425445902633376e-07}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:22:35,529] Trial 4 finished with value: 0.14274120640197896 and parameters: {'n_estimators': 400, 'learning_rate': 0.08580222514877409, 'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.6523068845866853, 'colsample_bytree': 0.2781376912051071, 'reg_alpha': 0.0029775853025212607, 'reg_lambda': 9.148975058772307e-05}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:22:40,453] Trial 5 finished with value: 0.13868453742364534 and parameters: {'n_estimators': 500, 'learning_rate': 0.022039920190846215, 'max_depth': 2, 'min_child_weight': 10, 'subsample': 0.6293899908000085, 'colsample_bytree': 0.7300178274831857, 'reg_alpha': 3.116654126398047e-06, 'reg_lambda': 0.0004793052550782129}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:22:57,676] Trial 6 finished with value: 0.14069265261403888 and parameters: {'n_estimators': 1200, 'learning_rate': 0.008699037355645861, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.915861880342119, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 1.9809253750493907}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:23:02,700] Trial 7 finished with value: 0.1581819447649599 and parameters: {'n_estimators': 400, 'learning_rate': 0.008993931736681457, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.6943386448447411, 'colsample_bytree': 0.41707922541911674, 'reg_alpha': 0.04264813784432918, 'reg_lambda': 1.6247252885719427e-05}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:23:12,272] Trial 8 finished with value: 0.13605036178063412 and parameters: {'n_estimators': 800, 'learning_rate': 0.025411709798607296, 'max_depth': 2, 'min_child_weight': 9, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9895095492804138, 'reg_alpha': 0.015064619068942013, 'reg_lambda': 6.143857495033091e-07}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:23:16,564] Trial 9 finished with value: 0.1381689478769736 and parameters: {'n_estimators': 300, 'learning_rate': 0.057532041236250865, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.2592357213872723, 'reg_alpha': 7.374385355858303e-06, 'reg_lambda': 1.1036250149900698e-07}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:23:25,324] Trial 10 finished with value: 0.13790061993246178 and parameters: {'n_estimators': 600, 'learning_rate': 0.08004405460438699, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8665710929655568, 'colsample_bytree': 0.6258304315907968, 'reg_alpha': 2.4751963034724222e-08, 'reg_lambda': 0.00018937767306492542}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:23:35,570] Trial 11 finished with value: 0.13667215120111664 and parameters: {'n_estimators': 800, 'learning_rate': 0.0459695146968175, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.6589789188819276, 'colsample_bytree': 0.9782356881454033, 'reg_alpha': 0.2401785671178257, 'reg_lambda': 1.002604651592856e-06}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:23:46,472] Trial 12 finished with value: 0.136040204122236 and parameters: {'n_estimators': 900, 'learning_rate': 0.03427402636766566, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.7114999379816381, 'colsample_bytree': 0.5311462106759444, 'reg_alpha': 0.075605260729431, 'reg_lambda': 1.9875239442762277e-06}. Best is trial 2 with value: 0.13430261411320069.
[I 2026-10-26 17:23:58,206] Trial 13 finished with value: 0.1340876449446749 and parameters: {'n_estimators': 900, 'learning_rate': 0.018064783711348474, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.8165718098214828, 'colsample_bytree': 0.32817735957792743, 'reg_alpha': 0.609160624203787, 'reg_lambda': 2.9813379807864054e-05}. Best is trial 13 with value: 0.1340876449446749.
[I 2026-10-26 17:24:13,101] Trial 14 finished with value: 0.13383270162782246 and parameters: {'n_estimators': 1100, 'learning_rate': 0.0111344123581089, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7732153242372303, 'colsample_bytree': 0.27847309783814944, 'reg_alpha': 0.14508829792909012, 'reg_lambda': 3.2000850879289074e-06}. Best is trial 14 with value: 0.13383270162782246.
[I 2026-10-26 17:24:22,284] Trial 15 finished with value: 0.1328760457851535 and parameters: {'n_estimators': 700, 'learning_rate': 0.02406472617109623, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.7164275909632369, 'colsample_bytree': 0.23146301733673436, 'reg_alpha': 0.33709777453840367, 'reg_lambda': 5.392139580829947e-07}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:24:26,569] Trial 16 finished with value: 0.1365283324140661 and parameters: {'n_estimators': 300, 'learning_rate': 0.030379678941066163, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.7311349590118136, 'colsample_bytree': 0.2087233602891867, 'reg_alpha': 0.09422151036732848, 'reg_lambda': 1.0809651151235715e-08}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:24:35,327] Trial 17 finished with value: 0.1336056194493298 and parameters: {'n_estimators': 600, 'learning_rate': 0.025923120303121855, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.5798868162816371, 'colsample_bytree': 0.26001543142460415, 'reg_alpha': 0.005050929196443431, 'reg_lambda': 3.894177332259321e-06}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:24:47,767] Trial 18 finished with value: 0.13591778260649404 and parameters: {'n_estimators': 900, 'learning_rate': 0.022708524232930162, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.5009388391453289, 'colsample_bytree': 0.27561311925911747, 'reg_alpha': 0.09185517747521837, 'reg_lambda': 2.1797061283114204e-07}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:24:54,612] Trial 19 finished with value: 0.13697994263134233 and parameters: {'n_estimators': 500, 'learning_rate': 0.016111069406237733, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.6210062292746427, 'colsample_bytree': 0.2812418622091267, 'reg_alpha': 0.005417576907649918, 'reg_lambda': 0.0005070644762073749}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:25:01,834] Trial 20 finished with value: 0.13478756156105914 and parameters: {'n_estimators': 500, 'learning_rate': 0.017190710858147294, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6595174510719513, 'colsample_bytree': 0.41826800103418793, 'reg_alpha': 0.3137860184976273, 'reg_lambda': 4.4172495542804046e-05}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:25:17,533] Trial 21 finished with value: 0.13446297438796223 and parameters: {'n_estimators': 1100, 'learning_rate': 0.009268325316914431, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8275403526144516, 'colsample_bytree': 0.2071906493227309, 'reg_alpha': 0.20271930067505428, 'reg_lambda': 6.703250285902232e-07}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:25:25,425] Trial 22 finished with value: 0.13461965454816766 and parameters: {'n_estimators': 600, 'learning_rate': 0.01882122691941883, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.7500942234076902, 'colsample_bytree': 0.2950159572967285, 'reg_alpha': 0.8191345672145643, 'reg_lambda': 1.4022449973819732e-07}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:25:38,976] Trial 23 finished with value: 0.13576570789321926 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02117978058328439, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7801672154862653, 'colsample_bytree': 0.29262766375901084, 'reg_alpha': 0.004467086655532603, 'reg_lambda': 1.9679236502492105e-06}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:25:50,469] Trial 24 finished with value: 0.13500805062113513 and parameters: {'n_estimators': 900, 'learning_rate': 0.011832047559129642, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.7448624215084586, 'colsample_bytree': 0.20467007793121117, 'reg_alpha': 0.012058479051656782, 'reg_lambda': 1.4805586275939242e-07}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:26:05,694] Trial 25 finished with value: 0.13420831295318386 and parameters: {'n_estimators': 1100, 'learning_rate': 0.0265198066394522, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8314648985323915, 'colsample_bytree': 0.2781895733595764, 'reg_alpha': 0.007810131869186598, 'reg_lambda': 1.8237839639255877e-05}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:26:18,720] Trial 26 finished with value: 0.13417354813815302 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05174180465933132, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.7315632037826295, 'colsample_bytree': 0.2097391292135912, 'reg_alpha': 0.5931793038940234, 'reg_lambda': 3.2900740189303556e-06}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:26:25,022] Trial 27 finished with value: 0.13474411463463812 and parameters: {'n_estimators': 500, 'learning_rate': 0.02378806422405889, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.5454024768342718, 'colsample_bytree': 0.27438294346131026, 'reg_alpha': 0.08409036870236763, 'reg_lambda': 1.7540687635013622e-05}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:26:31,584] Trial 28 finished with value: 0.13331592602401968 and parameters: {'n_estimators': 500, 'learning_rate': 0.05230362938036182, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.5266023472597855, 'colsample_bytree': 0.24220638903629962, 'reg_alpha': 0.16718950893134568, 'reg_lambda': 2.5659750844667964e-06}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:26:40,903] Trial 29 finished with value: 0.13423890597835733 and parameters: {'n_estimators': 700, 'learning_rate': 0.04919906483089179, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.5940363848832623, 'colsample_bytree': 0.20406113373010248, 'reg_alpha': 0.10689186956208706, 'reg_lambda': 1.4718873349918155e-06}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:26:51,325] Trial 30 finished with value: 0.1384451494243153 and parameters: {'n_estimators': 800, 'learning_rate': 0.07904927710817154, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.5913014336581814, 'colsample_bytree': 0.21478586696975074, 'reg_alpha': 0.0018522470230664112, 'reg_lambda': 3.9605435944144735e-06}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:27:02,466] Trial 31 finished with value: 0.1344940079321387 and parameters: {'n_estimators': 800, 'learning_rate': 0.055196537363613, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.5863345608010234, 'colsample_bytree': 0.35303139946116846, 'reg_alpha': 0.022576726416469208, 'reg_lambda': 7.277108737661418e-07}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:27:12,915] Trial 32 finished with value: 0.13449443654299795 and parameters: {'n_estimators': 800, 'learning_rate': 0.02443381918011263, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.5601449930828303, 'colsample_bytree': 0.4318543018996681, 'reg_alpha': 0.8026381342742906, 'reg_lambda': 1.7358598213314787e-06}. Best is trial 15 with value: 0.1328760457851535.
[I 2026-10-26 17:27:20,887] Trial 33 finished with value: 0.13254097995608513 and parameters: {'n_estimators': 600, 'learning_rate': 0.03251935393953634, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.5595051684996499, 'colsample_bytree': 0.38665464275192185, 'reg_alpha': 0.0728570758214033, 'reg_lambda': 6.59629732047599e-07}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:27:27,963] Trial 34 finished with value: 0.1354395328513604 and parameters: {'n_estimators': 500, 'learning_rate': 0.042775769721137, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.5968746295182158, 'colsample_bytree': 0.33760119509155173, 'reg_alpha': 0.24009003239290705, 'reg_lambda': 1.2103821920618964e-06}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:27:35,262] Trial 35 finished with value: 0.1365168234784176 and parameters: {'n_estimators': 600, 'learning_rate': 0.06817206191016452, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.510395604947365, 'colsample_bytree': 0.22857957985310545, 'reg_alpha': 0.011255850221643169, 'reg_lambda': 1.7811229190659341e-06}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:27:39,220] Trial 36 finished with value: 0.13451385387778036 and parameters: {'n_estimators': 300, 'learning_rate': 0.062136716199446024, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.5221929067484543, 'colsample_bytree': 0.2690388599202502, 'reg_alpha': 0.686462848847918, 'reg_lambda': 4.5907334676162297e-07}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:27:44,927] Trial 37 finished with value: 0.13507656327300407 and parameters: {'n_estimators': 400, 'learning_rate': 0.028857835338431725, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.5142165970360402, 'colsample_bytree': 0.29556489883441406, 'reg_alpha': 0.05095363694145474, 'reg_lambda': 0.00011389344307142406}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:27:50,237] Trial 38 finished with value: 0.13463718238754238 and parameters: {'n_estimators': 400, 'learning_rate': 0.029477613215412004, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.5849933660352997, 'colsample_bytree': 0.2679028067177933, 'reg_alpha': 0.04501602501750662, 'reg_lambda': 2.9421567020073186e-06}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:27:59,309] Trial 39 finished with value: 0.13283478110839408 and parameters: {'n_estimators': 700, 'learning_rate': 0.03695301505866804, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.5539124636120868, 'colsample_bytree': 0.2964995624845793, 'reg_alpha': 0.6862064036759863, 'reg_lambda': 3.675313117434644e-06}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:28:07,249] Trial 40 finished with value: 0.13326587122168818 and parameters: {'n_estimators': 600, 'learning_rate': 0.03894295561785399, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.5232490434845389, 'colsample_bytree': 0.42115703165528956, 'reg_alpha': 0.4430678223316927, 'reg_lambda': 7.330594562443681e-08}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:28:13,916] Trial 41 finished with value: 0.1334746248659789 and parameters: {'n_estimators': 500, 'learning_rate': 0.035871703833103764, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.5246355118418699, 'colsample_bytree': 0.40008856951688054, 'reg_alpha': 0.7301995553932707, 'reg_lambda': 5.064463873172874e-06}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:28:21,824] Trial 42 finished with value: 0.1334131931657025 and parameters: {'n_estimators': 600, 'learning_rate': 0.04557193024413473, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.5081377672119115, 'colsample_bytree': 0.36040529226031986, 'reg_alpha': 0.015898987193651102, 'reg_lambda': 2.3378387705415934e-05}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:28:26,000] Trial 43 finished with value: 0.13504317117697762 and parameters: {'n_estimators': 300, 'learning_rate': 0.049823222727361255, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.5276413479362483, 'colsample_bytree': 0.28657889578218915, 'reg_alpha': 0.020597671015703128, 'reg_lambda': 3.4808987699775066e-06}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:28:34,646] Trial 44 finished with value: 0.13318484703595393 and parameters: {'n_estimators': 700, 'learning_rate': 0.04534279789858453, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.5082591641344624, 'colsample_bytree': 0.30273891593901897, 'reg_alpha': 0.5762255880738786, 'reg_lambda': 4.175216226046782e-06}. Best is trial 33 with value: 0.13254097995608513.
[I 2026-10-26 17:28:44,787] Trial 45 finished with value: 0.13251344564301554 and parameters: {'n_estimators': 800, 'learning_rate': 0.05223821432478863, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.5812499537248361, 'colsample_bytree': 0.25197320400278816, 'reg_alpha': 0.7638059838786417, 'reg_lambda': 9.381158922418521e-06}. Best is trial 45 with value: 0.13251344564301554.
[I 2026-10-26 17:28:53,460] Trial 46 finished with value: 0.1320103075615242 and parameters: {'n_estimators': 700, 'learning_rate': 0.0395322210882127, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.5656165865903986, 'colsample_bytree': 0.26820212238059554, 'reg_alpha': 0.1525750636114867, 'reg_lambda': 0.0001221134496184683}. Best is trial 46 with value: 0.1320103075615242.
[I 2026-10-26 17:29:01,835] Trial 47 finished with value: 0.13346611390287316 and parameters: {'n_estimators': 600, 'learning_rate': 0.06242092079076985, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.5573870216265739, 'colsample_bytree': 0.2515469157595742, 'reg_alpha': 0.7362763100519066, 'reg_lambda': 7.61339556305034e-05}. Best is trial 46 with value: 0.1320103075615242.
[I 2026-10-26 17:29:11,393] Trial 48 finished with value: 0.13312738407873073 and parameters: {'n_estimators': 800, 'learning_rate': 0.0551405377555418, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.5876393140061791, 'colsample_bytree': 0.3192570358232945, 'reg_alpha': 0.024171682703563426, 'reg_lambda': 6.915053206262036e-05}. Best is trial 46 with value: 0.1320103075615242.
[I 2026-10-26 17:29:22,413] Trial 49 finished with value: 0.13396927922634957 and parameters: {'n_estimators': 900, 'learning_rate': 0.0704771043837672, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.5756917758489195, 'colsample_bytree': 0.2867716262136333, 'reg_alpha': 0.6366183746902861, 'reg_lambda': 5.326144576618215e-06}. Best is trial 46 with value: 0.1320103075615242.

Best RMSE:  0.1320103075615242
Best params:  {'n_estimators': 700, 'learning_rate': 0.0395322210882127, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.5656165865903986, 'colsample_bytree': 0.26820212238059554, 'reg_alpha': 0.1525750636114867, 'reg_lambda': 0.0001221134496184683}

# CatBoost

In [9]:
def objective_catboost(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 500, 2000, step=100),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'depth': trial.suggest_int('depth', 4, 8),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1.0, 20.0, log=True),
        'random_strength': trial.suggest_float('random_strength', 0.0, 2.0),
        'bagging_temperature': trial.suggest_float('bagging_temperature', 0.0, 1.0),
    }
    
    model = CatBoostRegressor(
        **params,
        random_state=42,
        verbose=0,                 # без лога каждой итерации
        allow_writing_files=False  # не создавать папку catboost_info
    )
    
    scores = cross_val_score(
        model, 
        X_train, 
        y_train, 
        cv=cv, 
        scoring='neg_root_mean_squared_error'
    )
    
    return -scores.mean()

In [10]:
study_catboost = optuna.create_study(
    direction='minimize',  # минимизируем RMSE
    sampler=optuna.samplers.TPESampler(seed=42)
)

study_catboost.optimize(objective_catboost, n_trials=50)
print('Best RMSE: ', study_catboost.best_value)
print('Best params: ', study_catboost.best_params)

[I 2026-10-26 17:29:22,449] A new study created in memory with name: no-name-1f3d9c42-6be9-4025-b4fb-6a9232c41030
[I 2026-10-26 17:29:41,593] Trial 0 finished with value: 0.1328015164036083 and parameters: {'iterations': 1000, 'learning_rate': 0.08927180304353628, 'depth': 7, 'l2_leaf_reg': 6.009974718380312, 'random_strength': 0.31203728088487304, 'bagging_temperature': 0.15599452033620265}. Best is trial 0 with value: 0.1328015164036083.
[I 2026-10-26 17:29:51,374] Trial 1 finished with value: 0.13465541620113913 and parameters: {'iterations': 500, 'learning_rate': 0.07348118405270448, 'depth': 7, 'l2_leaf_reg': 8.341106432362084, 'random_strength': 0.041168988591604894, 'bagging_temperature': 0.9699098521619943}. Best is trial 0 with value: 0.1328015164036083.
[I 2026-10-26 17:30:05,432] Trial 2 finished with value: 0.13353573314231504 and parameters: {'iterations': 1800, 'learning_rate': 0.016305687346221478, 'depth': 4, 'l2_leaf_reg': 1.7322667470546256, 'random_strength': 0.6084844859190754, 'bagging_temperature': 0.5247564316322378}. Best is trial 0 with value: 0.1328015164036083.
[I 2026-10-26 17:30:27,578] Trial 3 finished with value: 0.13247072628144674 and parameters: {'iterations': 1100, 'learning_rate': 0.019553708662745254, 'depth': 7, 'l2_leaf_reg': 1.5187479226722465, 'random_strength': 0.5842892970704363, 'bagging_temperature': 0.3663618432936917}. Best is trial 3 with value: 0.13247072628144674.
[I 2026-10-26 17:30:36,113] Trial 4 finished with value: 0.1345681382786571 and parameters: {'iterations': 1200, 'learning_rate': 0.06097839109531514, 'depth': 4, 'l2_leaf_reg': 4.666963767236923, 'random_strength': 1.184829137724085, 'bagging_temperature': 0.046450412719997725}. Best is trial 3 with value: 0.13247072628144674.
[I 2026-10-26 17:30:46,010] Trial 5 finished with value: 0.13904616852232018 and parameters: {'iterations': 1400, 'learning_rate': 0.014808945119975192, 'depth': 4, 'l2_leaf_reg': 17.16044502975481, 'random_strength': 1.9312640661491187, 'bagging_temperature': 0.8083973481164611}. Best is trial 3 with value: 0.13247072628144674.
[I 2026-10-26 17:31:02,773] Trial 6 finished with value: 0.13414590856115877 and parameters: {'iterations': 900, 'learning_rate': 0.012521954287060391, 'depth': 7, 'l2_leaf_reg': 3.738105868191796, 'random_strength': 0.24407646968955765, 'bagging_temperature': 0.4951769101112702}. Best is trial 3 with value: 0.13247072628144674.
[I 2026-10-26 17:31:07,638] Trial 7 finished with value: 0.13225374000453397 and parameters: {'iterations': 500, 'learning_rate': 0.08115595675970502, 'depth': 5, 'l2_leaf_reg': 7.277150634170934, 'random_strength': 0.6234221521788219, 'bagging_temperature': 0.5200680211778108}. Best is trial 7 with value: 0.13225374000453397.
[I 2026-10-26 17:31:44,764] Trial 8 finished with value: 0.1343072284670309 and parameters: {'iterations': 1300, 'learning_rate': 0.015305744365500184, 'depth': 8, 'l2_leaf_reg': 10.196967939171484, 'random_strength': 1.8789978831283782, 'bagging_temperature': 0.8948273504276488}. Best is trial 7 with value: 0.13225374000453397.
[I 2026-10-26 17:31:55,593] Trial 9 finished with value: 0.13591303435271812 and parameters: {'iterations': 1400, 'learning_rate': 0.0835361075531176, 'depth': 4, 'l2_leaf_reg': 1.7987863473362906, 'random_strength': 0.09045457782107613, 'bagging_temperature': 0.32533033076326434}. Best is trial 7 with value: 0.13225374000453397.
[I 2026-10-26 17:32:01,757] Trial 10 finished with value: 0.13926435366679674 and parameters: {'iterations': 600, 'learning_rate': 0.016983252645916384, 'depth': 5, 'l2_leaf_reg': 9.395398368297155, 'random_strength': 0.49965272051199716, 'bagging_temperature': 0.8004762119422482}. Best is trial 7 with value: 0.13225374000453397.
[I 2026-10-26 17:32:08,562] Trial 11 finished with value: 0.13199982368121335 and parameters: {'iterations': 500, 'learning_rate': 0.07338309364174002, 'depth': 6, 'l2_leaf_reg': 3.6840597426557835, 'random_strength': 0.5864550589158318, 'bagging_temperature': 0.6592690836357396}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:32:18,138] Trial 12 finished with value: 0.13329563342213915 and parameters: {'iterations': 500, 'learning_rate': 0.06251677191337845, 'depth': 7, 'l2_leaf_reg': 9.593089082328412, 'random_strength': 0.7011263180286411, 'bagging_temperature': 0.7473951577603606}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:32:24,859] Trial 13 finished with value: 0.13480517471765385 and parameters: {'iterations': 500, 'learning_rate': 0.08848914348627457, 'depth': 6, 'l2_leaf_reg': 2.166126026847167, 'random_strength': 0.4212055999788421, 'bagging_temperature': 0.7950668798877069}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:32:30,724] Trial 14 finished with value: 0.1327008065212777 and parameters: {'iterations': 600, 'learning_rate': 0.09851947210616561, 'depth': 5, 'l2_leaf_reg': 7.7489810018478416, 'random_strength': 0.6864853072418572, 'bagging_temperature': 0.424750948403662}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:32:37,479] Trial 15 finished with value: 0.13351131437239733 and parameters: {'iterations': 700, 'learning_rate': 0.06582091644553435, 'depth': 5, 'l2_leaf_reg': 9.913723423059386, 'random_strength': 0.6557064408462114, 'bagging_temperature': 0.6674790262724244}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:32:44,282] Trial 16 finished with value: 0.13303404058215973 and parameters: {'iterations': 500, 'learning_rate': 0.04363158908730281, 'depth': 6, 'l2_leaf_reg': 1.9905497443437827, 'random_strength': 0.8735191963045864, 'bagging_temperature': 0.3576547090820548}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:32:53,579] Trial 17 finished with value: 0.1335600888738981 and parameters: {'iterations': 700, 'learning_rate': 0.05904433601744352, 'depth': 6, 'l2_leaf_reg': 5.6108107683342405, 'random_strength': 0.14741170340256265, 'bagging_temperature': 0.6117073841355247}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:32:57,301] Trial 18 finished with value: 0.13347723157625618 and parameters: {'iterations': 500, 'learning_rate': 0.048015185369970396, 'depth': 4, 'l2_leaf_reg': 3.766338766205784, 'random_strength': 0.5281411080774986, 'bagging_temperature': 0.5498811538788555}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:33:04,054] Trial 19 finished with value: 0.1329902351306195 and parameters: {'iterations': 500, 'learning_rate': 0.07937311314506244, 'depth': 6, 'l2_leaf_reg': 2.2511342307856053, 'random_strength': 1.1093304123613166, 'bagging_temperature': 0.5981815821919889}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:33:11,317] Trial 20 finished with value: 0.13348002613937987 and parameters: {'iterations': 700, 'learning_rate': 0.04892442284280191, 'depth': 5, 'l2_leaf_reg': 6.863283356573946, 'random_strength': 0.5450988522542813, 'bagging_temperature': 0.2656619253710292}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:33:16,768] Trial 21 finished with value: 0.1353641407006138 and parameters: {'iterations': 700, 'learning_rate': 0.09511694639660727, 'depth': 4, 'l2_leaf_reg': 4.171452164659105, 'random_strength': 0.4417525413351373, 'bagging_temperature': 0.5514851910962629}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:33:21,647] Trial 22 finished with value: 0.1333140356070486 and parameters: {'iterations': 500, 'learning_rate': 0.08165969196870085, 'depth': 5, 'l2_leaf_reg': 13.904934980958236, 'random_strength': 0.4642155757195616, 'bagging_temperature': 0.4989681701778583}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:33:35,921] Trial 23 finished with value: 0.13355406550870735 and parameters: {'iterations': 1100, 'learning_rate': 0.07331387729742045, 'depth': 6, 'l2_leaf_reg': 7.620215993291251, 'random_strength': 0.7112905010661456, 'bagging_temperature': 0.5453271389379865}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:33:40,862] Trial 24 finished with value: 0.13456804960352348 and parameters: {'iterations': 500, 'learning_rate': 0.0664633563419367, 'depth': 5, 'l2_leaf_reg': 17.26567057166086, 'random_strength': 0.8795417735676929, 'bagging_temperature': 0.5882249927875169}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:33:45,840] Trial 25 finished with value: 0.13441281922728227 and parameters: {'iterations': 500, 'learning_rate': 0.08378817402897902, 'depth': 5, 'l2_leaf_reg': 12.454603562148822, 'random_strength': 0.26927260765965505, 'bagging_temperature': 0.24080152780813147}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:33:50,716] Trial 26 finished with value: 0.13737944508581976 and parameters: {'iterations': 500, 'learning_rate': 0.04032046437995634, 'depth': 5, 'l2_leaf_reg': 17.03171714413308, 'random_strength': 0.3968660221786634, 'bagging_temperature': 0.5062065004056073}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:33:57,229] Trial 27 finished with value: 0.13363173177187956 and parameters: {'iterations': 500, 'learning_rate': 0.06099820590148545, 'depth': 6, 'l2_leaf_reg': 6.831713721331937, 'random_strength': 0.5629038797626282, 'bagging_temperature': 0.4055705435638721}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:34:01,635] Trial 28 finished with value: 0.1347370218398984 and parameters: {'iterations': 600, 'learning_rate': 0.09406025546743657, 'depth': 4, 'l2_leaf_reg': 7.8593037921957825, 'random_strength': 0.46813576998286366, 'bagging_temperature': 0.6262145449272492}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:34:11,933] Trial 29 finished with value: 0.13324355276764785 and parameters: {'iterations': 1000, 'learning_rate': 0.06238250287665013, 'depth': 5, 'l2_leaf_reg': 5.300385250268172, 'random_strength': 0.44570249218078506, 'bagging_temperature': 0.5184537600064758}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:34:22,927] Trial 30 finished with value: 0.1327213782023569 and parameters: {'iterations': 800, 'learning_rate': 0.05447633901399508, 'depth': 6, 'l2_leaf_reg': 17.07813563449791, 'random_strength': 0.3105022636045249, 'bagging_temperature': 0.6507273957773585}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:34:32,961] Trial 31 finished with value: 0.13327248191373972 and parameters: {'iterations': 1000, 'learning_rate': 0.061933753992631346, 'depth': 5, 'l2_leaf_reg': 6.429009152573791, 'random_strength': 0.8571579723997191, 'bagging_temperature': 0.43575902425706936}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:34:38,962] Trial 32 finished with value: 0.13226818689736863 and parameters: {'iterations': 600, 'learning_rate': 0.059899822725128456, 'depth': 5, 'l2_leaf_reg': 6.424919415887469, 'random_strength': 0.9531862126819262, 'bagging_temperature': 0.5524906156211762}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:34:44,043] Trial 33 finished with value: 0.1337448176084189 and parameters: {'iterations': 500, 'learning_rate': 0.04454859913278535, 'depth': 5, 'l2_leaf_reg': 5.59990724113578, 'random_strength': 0.7541214317238024, 'bagging_temperature': 0.6223459802884875}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:34:49,295] Trial 34 finished with value: 0.13249045469236828 and parameters: {'iterations': 500, 'learning_rate': 0.056258825136653964, 'depth': 5, 'l2_leaf_reg': 3.7535504086229468, 'random_strength': 0.8599648532547792, 'bagging_temperature': 0.4441138150791992}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:34:57,397] Trial 35 finished with value: 0.13432154003126867 and parameters: {'iterations': 600, 'learning_rate': 0.09821147773827821, 'depth': 6, 'l2_leaf_reg': 4.603880389296067, 'random_strength': 0.6833169029904125, 'bagging_temperature': 0.6781498592087541}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:35:04,311] Trial 36 finished with value: 0.13256907988676433 and parameters: {'iterations': 700, 'learning_rate': 0.06205517203631859, 'depth': 5, 'l2_leaf_reg': 3.7386525728206457, 'random_strength': 0.681963060794057, 'bagging_temperature': 0.5954256820688689}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:35:15,068] Trial 37 finished with value: 0.1338353863984044 and parameters: {'iterations': 800, 'learning_rate': 0.08555247314987639, 'depth': 6, 'l2_leaf_reg': 13.028074200049543, 'random_strength': 0.6385897221543724, 'bagging_temperature': 0.4756803144779354}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:35:21,151] Trial 38 finished with value: 0.1340449938650094 and parameters: {'iterations': 600, 'learning_rate': 0.07780607099432794, 'depth': 5, 'l2_leaf_reg': 5.128452007146033, 'random_strength': 0.30832560969605927, 'bagging_temperature': 0.5250038685225383}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:35:26,537] Trial 39 finished with value: 0.13348659203897334 and parameters: {'iterations': 500, 'learning_rate': 0.07726394809814655, 'depth': 5, 'l2_leaf_reg': 10.24336467487275, 'random_strength': 1.2539588300718414, 'bagging_temperature': 0.46560086503056974}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:35:34,906] Trial 40 finished with value: 0.13305273625573077 and parameters: {'iterations': 600, 'learning_rate': 0.05396730501362121, 'depth': 6, 'l2_leaf_reg': 6.393628524469415, 'random_strength': 0.8724712651629545, 'bagging_temperature': 0.5135981972386381}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:35:40,884] Trial 41 finished with value: 0.13457852547315854 and parameters: {'iterations': 600, 'learning_rate': 0.09613275239709725, 'depth': 5, 'l2_leaf_reg': 2.46574406932387, 'random_strength': 0.8039314691292471, 'bagging_temperature': 0.6423956859047026}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:35:47,867] Trial 42 finished with value: 0.13239371728730706 and parameters: {'iterations': 700, 'learning_rate': 0.05001452031798736, 'depth': 5, 'l2_leaf_reg': 10.054292458249812, 'random_strength': 0.9065721852150541, 'bagging_temperature': 0.485978462536679}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:35:54,718] Trial 43 finished with value: 0.1331259020545137 and parameters: {'iterations': 500, 'learning_rate': 0.05528023344780723, 'depth': 6, 'l2_leaf_reg': 5.576305273902902, 'random_strength': 0.9821969650092888, 'bagging_temperature': 0.6432732865402058}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:35:59,797] Trial 44 finished with value: 0.13308462247979552 and parameters: {'iterations': 500, 'learning_rate': 0.06848812282499275, 'depth': 5, 'l2_leaf_reg': 5.6628920892101595, 'random_strength': 0.641360294676965, 'bagging_temperature': 0.5450219632159944}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:36:06,704] Trial 45 finished with value: 0.1338191825051896 and parameters: {'iterations': 500, 'learning_rate': 0.08496637003586925, 'depth': 6, 'l2_leaf_reg': 7.5730044152736395, 'random_strength': 0.9432796769956067, 'bagging_temperature': 0.5509727924348636}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:36:13,421] Trial 46 finished with value: 0.13323875386364575 and parameters: {'iterations': 500, 'learning_rate': 0.05810705246898892, 'depth': 6, 'l2_leaf_reg': 9.300511609331867, 'random_strength': 1.0895847653904989, 'bagging_temperature': 0.5048778137211634}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:36:20,408] Trial 47 finished with value: 0.13272744112828108 and parameters: {'iterations': 700, 'learning_rate': 0.05144358656568753, 'depth': 5, 'l2_leaf_reg': 10.564068138023575, 'random_strength': 0.9660276456389365, 'bagging_temperature': 0.5246727297585877}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:36:27,421] Trial 48 finished with value: 0.13284516780197622 and parameters: {'iterations': 700, 'learning_rate': 0.08360920029685641, 'depth': 5, 'l2_leaf_reg': 5.196865434571085, 'random_strength': 0.8719468193579727, 'bagging_temperature': 0.5075793836132122}. Best is trial 11 with value: 0.13199982368121335.
[I 2026-10-26 17:36:34,341] Trial 49 finished with value: 0.13287828551370834 and parameters: {'iterations': 700, 'learning_rate': 0.051864924094597156, 'depth': 5, 'l2_leaf_reg': 9.052236146350078, 'random_strength': 0.7443162839795909, 'bagging_temperature': 0.4781669758881878}. Best is trial 11 with value: 0.13199982368121335.

Best RMSE:  0.13199982368121335
Best params:  {'iterations': 500, 'learning_rate': 0.07338309364174002, 'depth': 6, 'l2_leaf_reg': 3.6840597426557835, 'random_strength': 0.5864550589158318, 'bagging_temperature': 0.6592690836357396}

# Lasso

In [11]:
def objective_lasso(trial):
    params = {
        'alpha': trial.suggest_float('alpha', 1e-5, 1e-2, log=True),
    }
    
    model = Lasso(
        **params,
        max_iter=50000,  # чтобы при маленьких alpha модель успевала сойтись
        random_state=42
    )
    
    scores = cross_val_score(
        model, 
        X_train, 
        y_train, 
        cv=cv, 
        scoring='neg_root_mean_squared_error'
    )
    
    return -scores.mean()

In [12]:
study_lasso = optuna.create_study(
    direction='minimize',  # минимизируем RMSE
    sampler=optuna.samplers.TPESampler(seed=42)
)

study_lasso.optimize(objective_lasso, n_trials=50)
print('Best RMSE: ', study_lasso.best_value)
print('Best params: ', study_lasso.best_params)

[I 2026-10-26 17:36:34,374] A new study created in memory with name: no-name-e72afb17-c272-4846-b41a-f0df81d7e003
[I 2026-10-26 17:36:34,573] Trial 0 finished with value: 0.13572867839825004 and parameters: {'alpha': 0.0001329291894316216}. Best is trial 0 with value: 0.13572867839825004.
[I 2026-10-26 17:36:34,675] Trial 1 finished with value: 0.14979271228984367 and parameters: {'alpha': 0.0071144760093434225}. Best is trial 0 with value: 0.13572867839825004.
[I 2026-10-26 17:36:34,789] Trial 2 finished with value: 0.14081743766140828 and parameters: {'alpha': 0.001570297088405539}. Best is trial 0 with value: 0.13572867839825004.
[I 2026-10-26 17:36:34,919] Trial 3 finished with value: 0.13525063226958672 and parameters: {'alpha': 0.0006251373574521745}. Best is trial 3 with value: 0.13525063226958672.
[I 2026-10-26 17:36:35,168] Trial 4 finished with value: 0.13755047596557976 and parameters: {'alpha': 2.9380279387035334e-05}. Best is trial 3 with value: 0.13525063226958672.
[I 2026-10-26 17:36:35,465] Trial 5 finished with value: 0.13755062407453772 and parameters: {'alpha': 2.9375384576328295e-05}. Best is trial 3 with value: 0.13525063226958672.
[I 2026-10-26 17:36:35,876] Trial 6 finished with value: 0.13809030374992337 and parameters: {'alpha': 1.493656855461762e-05}. Best is trial 3 with value: 0.13525063226958672.
[I 2026-10-26 17:36:36,003] Trial 7 finished with value: 0.14683305491052714 and parameters: {'alpha': 0.003967605077052989}. Best is trial 3 with value: 0.13525063226958672.
[I 2026-10-26 17:36:36,131] Trial 8 finished with value: 0.13532710601652675 and parameters: {'alpha': 0.0006358358856676254}. Best is trial 3 with value: 0.13525063226958672.
[I 2026-10-26 17:36:36,259] Trial 9 finished with value: 0.14005495330819767 and parameters: {'alpha': 0.001331121608073689}. Best is trial 3 with value: 0.13525063226958672.
[I 2026-10-26 17:36:36,435] Trial 10 finished with value: 0.13465730250108038 and parameters: {'alpha': 0.0002666012378440763}. Best is trial 10 with value: 0.13465730250108038.
[I 2026-10-26 17:36:36,610] Trial 11 finished with value: 0.13476198848236556 and parameters: {'alpha': 0.00024328915643291794}. Best is trial 10 with value: 0.13465730250108038.
[I 2026-10-26 17:36:36,822] Trial 12 finished with value: 0.13558980488287034 and parameters: {'alpha': 0.00014255751309842524}. Best is trial 10 with value: 0.13465730250108038.
[I 2026-10-26 17:36:37,039] Trial 13 finished with value: 0.1353969235062327 and parameters: {'alpha': 0.00015740268142215038}. Best is trial 10 with value: 0.13465730250108038.
[I 2026-10-26 17:36:37,232] Trial 14 finished with value: 0.13466440788702488 and parameters: {'alpha': 0.00026456534799476644}. Best is trial 10 with value: 0.13465730250108038.
[I 2026-10-26 17:36:37,438] Trial 15 finished with value: 0.1344858714092846 and parameters: {'alpha': 0.0003753211881795297}. Best is trial 15 with value: 0.1344858714092846.
[I 2026-10-26 17:36:37,604] Trial 16 finished with value: 0.136785287389298 and parameters: {'alpha': 5.83889111222153e-05}. Best is trial 15 with value: 0.1344858714092846.
[I 2026-10-26 17:36:37,728] Trial 17 finished with value: 0.13627384932594733 and parameters: {'alpha': 0.0007451617972708867}. Best is trial 15 with value: 0.1344858714092846.
[I 2026-10-26 17:36:37,950] Trial 18 finished with value: 0.1366876643709147 and parameters: {'alpha': 6.464994767421788e-05}. Best is trial 15 with value: 0.1344858714092846.
[I 2026-10-26 17:36:38,123] Trial 19 finished with value: 0.1344845188320716 and parameters: {'alpha': 0.0003799934985576666}. Best is trial 19 with value: 0.1344845188320716.
[I 2026-10-26 17:36:38,237] Trial 20 finished with value: 0.1450676695844036 and parameters: {'alpha': 0.0030460332947477484}. Best is trial 19 with value: 0.1344845188320716.
[I 2026-10-26 17:36:38,386] Trial 21 finished with value: 0.1345250830890704 and parameters: {'alpha': 0.00032095891662131085}. Best is trial 19 with value: 0.1344845188320716.
[I 2026-10-26 17:36:38,622] Trial 22 finished with value: 0.1344904620233511 and parameters: {'alpha': 0.0003532721272200655}. Best is trial 19 with value: 0.1344845188320716.
[I 2026-10-26 17:36:38,759] Trial 23 finished with value: 0.13457302978731664 and parameters: {'alpha': 0.000480562235559939}. Best is trial 19 with value: 0.1344845188320716.
[I 2026-10-26 17:36:38,896] Trial 24 finished with value: 0.13989299787471 and parameters: {'alpha': 0.0012849269844174586}. Best is trial 19 with value: 0.1344845188320716.
[I 2026-10-26 17:36:39,072] Trial 25 finished with value: 0.13636393328923052 and parameters: {'alpha': 8.531488125242356e-05}. Best is trial 19 with value: 0.1344845188320716.
[I 2026-10-26 17:36:39,219] Trial 26 finished with value: 0.13448085076274408 and parameters: {'alpha': 0.0003845531758073437}. Best is trial 26 with value: 0.13448085076274408.
[I 2026-10-26 17:36:39,407] Trial 27 finished with value: 0.13800676828957453 and parameters: {'alpha': 0.0009413741568391224}. Best is trial 26 with value: 0.13448085076274408.
[I 2026-10-26 17:36:39,531] Trial 28 finished with value: 0.14241095659784622 and parameters: {'alpha': 0.002049670274414756}. Best is trial 26 with value: 0.13448085076274408.
[I 2026-10-26 17:36:39,716] Trial 29 finished with value: 0.13609867433949333 and parameters: {'alpha': 0.0001069598255454438}. Best is trial 26 with value: 0.13448085076274408.
[I 2026-10-26 17:36:39,889] Trial 30 finished with value: 0.1352910081758693 and parameters: {'alpha': 0.00016675043821758853}. Best is trial 26 with value: 0.13448085076274408.
[I 2026-10-26 17:36:40,053] Trial 31 finished with value: 0.13446764910430792 and parameters: {'alpha': 0.0004197347797080614}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:40,190] Trial 32 finished with value: 0.13447414025707735 and parameters: {'alpha': 0.0003932930180752019}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:40,337] Trial 33 finished with value: 0.1345145008601632 and parameters: {'alpha': 0.0004585137042550925}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:40,461] Trial 34 finished with value: 0.13808039239872955 and parameters: {'alpha': 0.0009496609496690263}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:40,619] Trial 35 finished with value: 0.13507244341923846 and parameters: {'alpha': 0.0001926515156046743}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:40,817] Trial 36 finished with value: 0.13477238833186067 and parameters: {'alpha': 0.0005417178728644991}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:40,956] Trial 37 finished with value: 0.15119407376678404 and parameters: {'alpha': 0.009728583151931043}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:41,092] Trial 38 finished with value: 0.137628580126542 and parameters: {'alpha': 0.00089752676716181}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:41,205] Trial 39 finished with value: 0.1440670225543444 and parameters: {'alpha': 0.0025983219530999126}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:41,378] Trial 40 finished with value: 0.13497531473915597 and parameters: {'alpha': 0.00020624835931819076}. Best is trial 31 with value: 0.13446764910430792.
[I 2026-10-26 17:36:41,541] Trial 41 finished with value: 0.13446674956717372 and parameters: {'alpha': 0.0004050358187113016}. Best is trial 41 with value: 0.13446674956717372.
[I 2026-10-26 17:36:41,705] Trial 42 finished with value: 0.1344738193637638 and parameters: {'alpha': 0.00043152529824586847}. Best is trial 41 with value: 0.13446674956717372.
[I 2026-10-26 17:36:41,848] Trial 43 finished with value: 0.13571535517119532 and parameters: {'alpha': 0.000683859129362191}. Best is trial 41 with value: 0.13446674956717372.
[I 2026-10-26 17:36:41,998] Trial 44 finished with value: 0.14015356105179694 and parameters: {'alpha': 0.0013581012699364165}. Best is trial 41 with value: 0.13446674956717372.
[I 2026-10-26 17:36:42,160] Trial 45 finished with value: 0.13600872751074267 and parameters: {'alpha': 0.00011504070681516706}. Best is trial 41 with value: 0.13446674956717372.
[I 2026-10-26 17:36:42,304] Trial 46 finished with value: 0.1346307046424588 and parameters: {'alpha': 0.00027537567931808736}. Best is trial 41 with value: 0.13446674956717372.
[I 2026-10-26 17:36:42,457] Trial 47 finished with value: 0.13467237919924568 and parameters: {'alpha': 0.0005128496970893043}. Best is trial 41 with value: 0.13446674956717372.
[I 2026-10-26 17:36:42,726] Trial 48 finished with value: 0.13733261179374076 and parameters: {'alpha': 3.595664962278217e-05}. Best is trial 41 with value: 0.13446674956717372.
[I 2026-10-26 17:36:42,917] Trial 49 finished with value: 0.13481876217035918 and parameters: {'alpha': 0.00023281186604496087}. Best is trial 41 with value: 0.13446674956717372.

Best RMSE:  0.13446674956717372
Best params:  {'alpha': 0.0004050358187113016}

In [13]:
res = pd.DataFrame(
    {'model_name': ['XGBoost', 'CatBoost', 'Lasso'],
     'rmse': [study_xgb.best_value, study_catboost.best_value, study_lasso.best_value]}
)
res.sort_values('rmse')

  model_name      rmse
1   CatBoost  0.132000
0    XGBoost  0.132010
2      Lasso  0.134467

# Final

In [14]:
test_data = pd.read_csv('../data/processed/test.csv')
test_raw = pd.read_csv('../data/raw/test.csv')

X = test_data.drop(columns=['Id'])

In [15]:
model = CatBoostRegressor(
    **study_catboost.best_params,
    random_state=42,
    verbose=0,                 # без лога каждой итерации
    allow_writing_files=False  # не создавать папку catboost_info
)

model.fit(X_train, y_train)

predictions = model.predict(X)
final_predictions = np.expm1(predictions)

In [16]:
submission = pd.DataFrame({
    'Id': test_raw['Id'],
    'SalePrice': final_predictions
})
submission

        Id      SalePrice
0     1461  125370.243932
1     1462  155457.205061
2     1463  182399.383351
3     1464  188579.588800
4     1465  188714.918336
...    ...            ...
1454  2915   76894.888209
1455  2916   80429.901302
1456  2917  153355.746548
1457  2918  114161.865379
1458  2919  223084.232856

[1459 rows x 2 columns]

In [17]:
os.makedirs('../submissions', exist_ok=True)

submission.to_csv('../submissions/submissioncatboost.csv', index=False)

In [18]:
results = pd.DataFrame({
    'Name': ['CatBoost', 'XGBoost', 'Lasso'],
    'CV': [study_catboost.best_value, study_xgb.best_value, study_lasso.best_value],
    'LB': [0.12901, None, None]
})

results

       Name        CV       LB
0  CatBoost  0.132000  0.12901
1   XGBoost  0.132010      NaN
2     Lasso  0.134467      NaN